Makefile

This makes it easier for downstream packagers to override these variables without patching.

Allow for overriding BIN, SBIN and MAN

---

Makefile

On OpenBSD we install the `vnstat.conf` into `/usr/local/share/examples/vnstat/` so we don't unconditionally overwrite `/etc/vnstat.conf`

make the path to vnstat.conf variable

---

src/dbjson.c

Just installed vnstat from the ArchLinux repository and did `$ vnstat --json|json_pp` shortly after starting the daemon. json_pp notified me of bad JSON data. Output as generated by vnstat --json (Removed irrelevant parts):
````
{"interfaces":[{"traffic":{"hours":[,{"id":19,"date":{"year":2015,"month":1,"day":28},"rx":7876,"tx":428}]}}]}
````
The 'hours' array begins with a comma (","), yielding illegal JSON data. The attached patch fixes all of these cases in dbjson.c.

Fix JSON output for new databases

---

src/vnstat.c

fixes:
````
Error: Database for interface "" already exists.
```

fix typo in --create duplication error message

---

src/dbshow.c

Also use a macro for its size.
Dates in some languages (e.g. Chinese) need larger buffers to contain
(for Chinese it usually needs at most 18 bytes). I've seen the month and
day display corrupted in Chinese or Japanese locales.
(PS: I hope I've replaced all relevant numbers with the macro.)

use larger buffers for date display

---

aclocal.m4
configure
configure.ac

Even when the gd library is present, it may be desirable to not build
'vnstati' as image output is an optional feature.
Also, when testing for the gd library, use gdImagePng() instead of
gdImageLine() since it's possible that the installed gd library doesn't
have PNG support. In such cases, the test in the configure script passed
(because gdImageLine() is always present), but the build failed with:
src/vnstati.o: In function 'writeoutput':
vnstati.c:(.text+0x3fc): undefined reference to 'gdImagePng'
collect2: error: ld returned 1 exit status

configure.ac: add option to disable image output

---

Makefile.am

Forwarded from https://bugs.debian.org/859712
Calling $(DESTDIR)$(bindir)/vnstat$(EXEEXT) fails when installation of this
program is not yet finished.
Author: Adrian Bunk <bunk@debian.org>

Makefile.am: install-data-hook depends on install-exec

---

src/cfg.c
src/daemon.c
src/dbcache.c
src/dbcache.h
src/fs.c
src/image.h
src/misc.h

* fix printf argument
found by cppcheck:
[src/cfg.c:66]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
* fix clang-tidy issues
src/image.h:12:22: warning: macro replacement list should be enclosed in parentheses [misc-macro-parentheses]
src/misc.h:8:20: warning: all parameters should be named in a function [readability-named-parameter]
src/fs.h:7:6: warning: function 'preparevnstatdir' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name]
* fix compile warnings
src/daemon.c:176:13: warning: use of non-standard escape character '\%' [-Wpedantic]
src/dbcache.c:333:33: warning: declaration shadows a variable in the global scope [-Wshadow]

fix several warnings from tools

---

src/dbcache.c

[src/dbcache.c:166]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.

fix cppcheck note

---

man/vnstat.1

Hi, I just noticed that leftover --delete in the man.

Remove --delete option from manpage

---

man/vnstat.1

Fix typo `today` with `current month`
```
--oneline
Show  traffic  summary  for  selected  interface  using one line with a
parseable format. The output contains 15 fields with ;  used  as  field
delimiter. The 1st field contains the version information of the output
that will be changed in future versions of vnStat if the  field  struc‐
ture changes. The following fields in order 2) interface name, 3) time‐
stamp for today, 4) rx for today, 5) tx for today, 6) total for  today,
7)  average  traffic rate for today, 8) timestamp for current month, 9)
rx for current month, 10) tx for current month, 11) total  for  current
month,  12)  average traffic rate for today, 13) all time total rx, 14)
all time total tx, 15) all time total traffic.  An optional mode param‐
eter  can  be  used  to …
```

man/vnstat.1: fix typo today with current month

---

src/dbsql.c
src/fs.c

*  fix resource leak in db_getdata_range
if an invalid 'table' is given the function returns without freeing 'ifaceidin'
postpone the initialization
*  fix resource leak in db_getinterfaceinfo
if 'ifaceidin' gets initialized but it's length is 0, it is not freed
*  fix double close in updatedirownerid
after successfully passing 'dir_fd' to 'fdopendir' is must not be closed manually

fix Coverity findings

---

.travis.yml
src/daemon.c
src/daemon.h
src/dbsql.c
src/misc.c
tests/daemon_tests.c

Fix one off-by-one-read and silence multiple findings by running the testsuite with clang's sanitizers.
Reproduce:
```
CC="clang -Wall -Wextra -O1 -g -fsanitize=address -fno-omit-frame-pointer -fsanitize=undefined -fsanitize=nullability -fsanitize=implicit-conversion -fsanitize=integer" ./configure
make check
```
Edit: Also add a sanitizer build for travis-ci

run testsuite with sanitizers

---

.travis.yml

also use `osx_image: xcode11` to get a working homebrew version

travis: switch to homebrew addon

---

Makefile.am

When executing `make check` in parallel, check-local might be executed before check-TESTS (the normal test suite) has finished.
That makes the printing of test.log useless.
Humans might be able to always run `make check` serially, but e.g. during a Debian package build every step runs parallelly.
Also fail check-local, if tailing test.log fails.
**Note**: this requires a regeneration of the autoconfig configuration files to take effect
Example output:
$ make -j check
Making check in .
make[1]: Entering directory '/home/christian/Coding/workspaces/smartgit/vnstat'
make  check_vnstat
make[2]: Entering directory '/home/christian/Coding/workspaces/smartgit/vnstat'
make[2]: Leaving directory '/home/christian/Coding/workspaces/smartgit/vnstat'
make  check-TESTS check-local
make[2]: Entering …

Check local

---

src/dbsql.c

gcc warnings:
```
src/dbsql.c: In function ‘db_create’:
src/dbsql.c:314:6: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
314 |  sql = "CREATE TABLE info(\n"
|      ^
src/dbsql.c:324:6: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
324 |  sql = "CREATE TABLE interface(\n"
|      ^
src/dbsql.c: In function ‘db_getiflist_sorted’:
src/dbsql.c:730:7: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
730 |   sql = "select name from interface order by name asc";
|       ^
src/dbsql.c:732:7: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
732 |   sql = "select name from interface order by …
```

avoid discarding const on const strings

---

src/ifinfo.c

E.g. vnStat compiles on hurd, but the testsuite fails ultimately

Error early on non Linux and BSD like systems

---

man/vnstat.conf.5

Currently the man page shows
```
'#`
```
, let show it
```
'#'
```
.
Found by Lintian (acute-accent-in-manual-page)
This manual page uses the \' groff sequence. Usually, the intent to
generate an apostrophe, but that sequence actually renders as a an acute
accent.
For an apostrophe or a single closing quote, use plain '. For single
opening quote, i.e. a straight downward line ' like the one used in
shell commands, use &#92;(aq.

vnstat.conf.5: use single closing '

---

src/vnstat_func.c

I was renaming my interface in vnstat from `enp8s0` to `enp9s0` as my network adapter changed names and noticed the wrong interface was being printed here.
It's supposed to print the newer interface's name - as it's an error regarding it already existing on the database.

rename: Correctly print existing interface

---

man/vnstatd.8

The code uses different paths than it was  mentioned there.

manpages: correct path

---

man/vnstat.conf.5
man/vnstatd.8
src/vnstatd.c

`man 5 vnstat.conf` lists under `CreateDirs`
>The PidFile directory will be created only if the daemon is started as a background process.
It would be nice to also mention that this file is not used at:
The second commit will throw an error when the option is used at the wrong time, to warn users that it wouldn't do what they expect.
But the real question is rather: Should it behave the way it currently does? Maybe it should always create the lockfile?
With the systemd service, `--nodaemon` is used to avoid the process forking away. So that the stdour/stderr will go into the journal of that unit.

Document that the pidfile is only created when running with --daemon

---

src/image.c
src/image_support.c
src/image_support.h

```
src/image.c: In function 'drawfiveminutes':
src/image.c:973:20: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
973 |   printf("maxrx: %lu\n", datainfo.maxrx);
|                  ~~^     ~~~~~~~~~~~~~~
|                    |             |
|                    |             uint64_t {aka long long unsigned int}
|                    long unsigned int
|                  %llu
src/image.c:974:20: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
974 |   printf("maxtx: %lu\n", datainfo.maxtx);
|                  ~~^     ~~~~~~~~~~~~~~
|                    |             |
|                    | …
```

Use correct format length specifiers for 32-bit systems

---

src/dbsql.c
src/image.c

These are variables are always re-set before a next read.

Remove dead stores to variables

---

src/image_support.c
src/image_support.h

tests/image_tests.c: In function ‘hextorgb_can_convert_fn’:
tests/image_tests.c:738:18: warning: passing argument 1 of ‘hextorgb’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
738 |         hextorgb(000000, rgb);
|                  ^~~~~~~~
In file included from tests/image_tests.c:7:
./src/image_support.h:18:21: note: expected ‘char *’ but argument is of type ‘const char *’
18 | void hextorgb(char *input, int *rgb);
|               ~~~~~~^~~~~

Mark input argument to hextorgb const

---

src/cfg.c

Only the gather the requested environment variable once, since it should not
change between calls.
Also silences clang-analyzer warnings:
src/cfg.c:561:7: warning: Null pointer passed to 1st parameter expecting 'nonnull' [core.NonNullParamChecker]
if (strstr(getenv(LC_ALL), UTF) != NULL) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cache environment variable

---

tests/vnstat_tests.c

readdir(3) may not determine the type of the returned entry, quoting man:readdir(3):
Currently, only some filesystems (among them: Btrfs, ext2, ext3, and
ext4) have full support for returning the file type in d_type. All
applications must properly handle a return of DT_UNKNOWN.
This happens for example in the Debian salsa-ci for reproducible builds.

handle DT_UNKNOWN type entries in remove_directory

---

configure
configure.ac

change GNU expr-specific syntax from `match STRING REGEXP' to the equivalent `STRING : REGEXP' for compatibility with OpenBSD expr

expr syntax compatibility with GNU and OpenBSD

---

man/vnstat.1
man/vnstatd.8

Reported by Lintian:
$ LC_ALL=C.UTF-8 MANROFFSEQ='' MANWIDTH=80 man --warnings -E UTF-8 -l -Tutf8 -Z ./man/vnstat.1 >/dev/null
an.tmac:<standard input>:600: warning: tbl preprocessor failed, or it or soelim was not run; table(s) likely not rendered (TE macro called with TW register undefined)
See https://lists.debian.org/debian-devel/2023/08/msg00220.html

man: run the tbl preprocessor to silence groff warning
